version: "3.5"
services:
  spark-master:
    volumes:
      - /home/jga/docker-volumes/spark:/srv

  spark-worker:
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
    volumes:
      - /home/jga/docker-volumes/spark:/srv

  spark-driver:
    build:
      context: .
    command: wait-for-it -h spark-master -p 7077 -s -- spark-submit --class org.apache.spark.examples.JavaSparkPi /srv/spark-examples_2.11-2.2.1.jar 
    volumes:
      - /home/jga/docker-volumes/spark:/srv
    networks:
      - spark-net
