version: "3.5"
services:
  spark-master:
    build:
      context: .
    hostname: spark-master  
    command: start-master.sh
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    networks:
      - spark-net

  spark-worker:
    build:
      context: .
    command: start-slave.sh spark://spark-master:7077
    networks:
      - spark-net

networks:
  spark-net:
   name: spark-net
